# Generated by Django 4.1.3 on 2022-11-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_rename_checkings_checking_rename_savings_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='c_acc_holder',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='checking',
            name='c_acc_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='checking',
            name='c_acc_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checking',
            name='c_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checking',
            name='c_bank',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='checking',
            name='c_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checking',
            name='c_debit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checking',
            name='c_purpose',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='s_acc_holder',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='s_acc_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='s_acc_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='s_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='s_bank',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='s_debit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
