# Generated by Django 4.1.3 on 2022-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_checking_c_acc_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checking',
            name='c_debit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
