# Generated by Django 4.1.3 on 2022-11-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0005_saving_s_debit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='c_debit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='s_debit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_account_name', models.CharField(max_length=50)),
                ('cr_amount', models.IntegerField()),
                ('cr_purpose', models.TextField(max_length=250)),
                ('cr_bank_name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
