# Generated by Django 4.1.3 on 2022-11-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_alter_checking_c_debit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='cr_acc_no',
            field=models.IntegerField(default=1),
        ),
    ]
