# Generated by Django 4.1.3 on 2022-11-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_credit_cr_acc_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
