# Generated by Django 4.1.3 on 2022-11-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='s_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
