# Generated by Django 4.1.3 on 2022-11-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_alter_saving_s_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='checking',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='transfer.checking'),
        ),
        migrations.AddField(
            model_name='saving',
            name='external_trans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
