# Generated by Django 4.1.3 on 2022-11-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_saving_checking_saving_external_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='checking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transfer.checking'),
        ),
    ]
