# Generated by Django 4.1.3 on 2022-11-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_alter_saving_checking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='checking',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='external_trans',
        ),
    ]
